services:
  - type: web
    name: life-tracker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
databases:
  - name: life-tracker-db
    databaseName: lifetracker
    user: lifetracker
